### ISSUE TITLE
Link to download the ODT is dead

### ISSUE THREAD

**Issue by maxrock18** [mallockey/Install-Microsoft365#19]
The link to download the ODT-->https://www.microsoft.com/en-us/download/details.aspx?id=49117 is dead.

As such, the installation cannot proceed.

**Comment by mallockey** [comment]
Thank you for catching this!

I have a PR open here for this

**Comment by mallockey** [comment]
Merged the PR, this should be resolved now

**Comment by maxrock18** [comment]
@mallockey Yes, Great fix. Small suggestion in case MS breaks the link again. You may want to include the link that is leveraged by the [Office Configuration Service Provider (CSP)](https://learn.microsoft.com/en-us/windows/client-management/mdm/office-csp) to download the ODT-->http://go.microsoft.com/fwlink/?LinkID=829801. It gives you the uncompressed ODT only.
